spring:
  profiles:
    active: default
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CL17-I04-002/microservice-configs.git
          default-label: master
          clone-on-start: true
server:
  port: 7777
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/